# Generated by Django 4.0.3 on 2022-04-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('public', 'Public'), ('cv', 'CV Request'), ('meeting', 'Meeting'), ('project', 'New Project')], default='public', max_length=30)),
                ('body', models.TextField()),
                ('review', models.TextField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
