# Generated by Django 4.0.3 on 2022-04-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_contactme_options_alter_contactform_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='options',
            options={'verbose_name_plural': 'Options'},
        ),
        migrations.AddField(
            model_name='contactme',
            name='fontawesome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
