# Generated by Django 4.0.3 on 2022-04-03 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_alter_options_options_contactme_fontawesome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactMe',
            new_name='ContactInfo',
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name_plural': 'Contact Info'},
        ),
    ]
