# Generated by Django 4.0.3 on 2022-04-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_rename_contactme_contactinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
