# Generated by Django 4.0.3 on 2022-04-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_skill_created_at_skill_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
