# Generated by Django 4.0.3 on 2022-04-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='body',
            field=models.TextField(default=None),
        ),
    ]
