# Generated by Django 4.0.3 on 2022-04-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_experience_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='finish_date',
            field=models.DateField(null=True),
        ),
    ]
