# Generated by Django 4.0.3 on 2022-04-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0011_alter_experience_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
