# Generated by Django 4.0.3 on 2022-04-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_certificate_education_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='color',
            field=models.CharField(blank=True, default=True, max_length=8),
        ),
    ]
