# Generated by Django 4.0.3 on 2022-04-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0015_alter_options_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='image',
            field=models.ImageField(upload_to='static/files'),
        ),
    ]
