# Generated by Django 4.0.3 on 2022-04-10 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0020_alter_skill_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='current',
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='mainsite.skillcategory'),
        ),
    ]
