# Generated by Django 4.1.7 on 2023-02-18 16:53

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0021_remove_experience_current_alter_skill_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='logo',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='contact_type',
            field=models.CharField(choices=[('sn', 'Social Network'), ('glance', 'Glance'), ('mail', 'Email'), ('phone', 'Phone'), ('others', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='education',
            name='logo',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='logo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
